# Generated by Django 4.1.3 on 2022-11-26 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_cart_product_productquntity_created_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productquntity',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='ProductQuntity',
        ),
    ]
