# Generated by Django 4.1.3 on 2022-11-26 23:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 11, 26, 23, 41, 52, 28256, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
